/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ProposalManager } from "./ProposalManager";
export * as factories from "./factories";
export { ProposalManager__factory } from "./factories/ProposalManager__factory";
